### ISSUE TITLE
Couldn't select Property as investment catagory or as exposure for a P&C insurer 

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#92] opened 2022-01-17 15:11 UTC
From Kate Newton,
There didn’t seem to be an option to select Property as an exposure for a P&C insurer. I would have thought Property was one of the most relevant categories of exposure for climate change and there is a section on Property underwriting in the report.
There also didn’t seem to be the option to select Property as an investment category to reflect a portfolio of investment properties held by some insurers. Are the risks for Investment Property (owned outright) captured under Commercial Real Estate mortgages?

**Comment by JohnAdders** [comment] 2022-01-24 08:30
Duplicate of #59

**Closed by JohnAdders** 2022-01-24 08:30 UTC
Labels: duplicate
